# Generated by Django 5.2.1 on 2025-05-26 13:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.FloatField(help_text='Calorías por 100g')),
                ('proteinas', models.FloatField(help_text='Proteínas por 100g')),
                ('grasas', models.FloatField(help_text='Grasas por 100g')),
                ('carbohidratos', models.FloatField(help_text='Carbohidratos por 100g')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad en gramos')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.alimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
