# Generated by Django 5.2.1 on 2025-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alimento_registroalimentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(help_text='Calorías por 100 g'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carbohidratos',
            field=models.FloatField(help_text='Carbohidratos por 100 g'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas',
            field=models.FloatField(help_text='Grasas por 100 g'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(help_text='Nombre del alimento', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(help_text='Proteínas por 100 g'),
        ),
    ]
