# Generated by Django 5.2.1 on 2025-05-27 20:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_alimento_calorias_alter_alimento_carbohidratos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroalimentacion',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Registro de Alimentación', 'verbose_name_plural': 'Registros de Alimentación'},
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(help_text='Calorías por 100 g', verbose_name='Calorías (por 100g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carbohidratos',
            field=models.FloatField(help_text='Carbohidratos por 100 g', verbose_name='Carbohidratos (por 100g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas',
            field=models.FloatField(help_text='Grasas por 100 g', verbose_name='Grasas (por 100g)'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(help_text='Nombre del alimento', max_length=100, unique=True, verbose_name='Nombre del alimento'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(help_text='Proteínas por 100 g', verbose_name='Proteínas (por 100g)'),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.alimento', verbose_name='Alimento'),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='cantidad',
            field=models.FloatField(help_text='Cantidad consumida en gramos', verbose_name='Cantidad (gramos)'),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='actividad_fisica',
            field=models.CharField(blank=True, help_text='Ej: Sedentario, ejercicio ligero 1-2/sem, etc.', max_length=100, null=True, verbose_name='Nivel de actividad física'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('def', 'Definición'), ('vol', 'Volumen'), ('man', 'Mantenimiento'), ('res', 'Resistencia')], max_length=20, null=True, verbose_name='Objetivo principal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo biológico'),
        ),
    ]
