# Generated by Django 5.2.1 on 2025-05-29 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_registroalimentacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalimentacion',
            name='tipo_comida',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('comida_mediodia', 'Comida'), ('cena', 'Cena'), ('snacks', 'Snacks')], default='comida_mediodia', max_length=20, null=True, verbose_name='Tipo de Comida'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calorias_ejercicio_hoy_registradas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calorias_ejercicio_semana_obj',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calorias_objetivo_fijadas',
            field=models.PositiveIntegerField(blank=True, default=2200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carbohidratos_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=265, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='entrenamientos_semana_obj',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grasas_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='minutos_ejercicio_obj',
            field=models.PositiveIntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proteinas_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=150, null=True),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de medición')),
                ('peso', models.FloatField(blank=True, help_text='Tu peso en kilogramos, ej: 70.5', null=True, verbose_name='Peso (kg)')),
                ('cuello', models.FloatField(blank=True, help_text='Circunferencia en centímetros', null=True, verbose_name='Medida de cuello (cm)')),
                ('cintura', models.FloatField(blank=True, help_text='Circunferencia en centímetros, a la altura del ombligo', null=True, verbose_name='Medida de cintura (cm)')),
                ('caderas', models.FloatField(blank=True, help_text='Circunferencia en la parte más ancha', null=True, verbose_name='Medida de caderas (cm)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Medida Corporal',
                'verbose_name_plural': 'Medidas Corporales',
                'ordering': ['usuario', '-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
