# Generated by Django 5.2.1 on 2025-05-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_registroalimentacion_tipo_comida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', null=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil'),
        ),
    ]
