# Generated by Django 5.2.1 on 2025-05-30 09:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroalimentacion',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name': 'Registro de Alimentación', 'verbose_name_plural': 'Registros de Alimentación'},
        ),
        migrations.AddField(
            model_name='registroalimentacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consumo'),
        ),
        migrations.AlterField(
            model_name='registroalimentacion',
            name='tipo_comida',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('comida', 'Comida'), ('cena', 'Cena'), ('snacks', 'Snacks')], max_length=20, null=True, verbose_name='Tipo de Comida'),
        ),
        migrations.CreateModel(
            name='ConsumoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('cantidad_ml', models.PositiveIntegerField(default=0, help_text='Cantidad total de agua consumida en mililitros', verbose_name='Cantidad (ml)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consumo de Agua',
                'verbose_name_plural': 'Consumos de Agua',
                'ordering': ['usuario', '-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
