# Generated by Django 5.2.1 on 2025-06-01 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_registroalimentacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Ejercicio')),
                ('tipo', models.CharField(choices=[('cardio', 'Cardiovascular'), ('fuerza', 'Fuerza')], max_length=10, verbose_name='Tipo de Ejercicio')),
                ('grupo_muscular', models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdominales', 'Abdominales'), ('cardio_general', 'Cardio General'), ('otro', 'Otro/Cuerpo Completo')], max_length=20, null=True, verbose_name='Grupo Muscular')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL del Video Explicativo')),
                ('calorias_quemadas_base', models.PositiveIntegerField(default=50, help_text='Para fuerza: kcal por sesión estándar. Para cardio: kcal por minuto.', verbose_name='Calorías Quemadas Base')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['grupo_muscular', 'tipo', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carbohidratos_objetivo_g',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grasas_objetivo_g',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='minutos_ejercicio_obj',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='proteinas_objetivo_g',
        ),
        migrations.AddField(
            model_name='usuario',
            name='minutos_ejercicio_obj_semana',
            field=models.PositiveIntegerField(blank=True, default=150, null=True, verbose_name='Minutos de Ejercicio Objetivo (Semanal)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='calorias_ejercicio_hoy_registradas',
            field=models.PositiveIntegerField(default=0, verbose_name='Calorías de Ejercicio Registradas Hoy (kcal)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='calorias_ejercicio_semana_obj',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='Calorías de Ejercicio Objetivo (Semanal)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='calorias_objetivo_fijadas',
            field=models.PositiveIntegerField(blank=True, default=2200, null=True, verbose_name='Objetivo de Ingesta Calórica (kcal)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='entrenamientos_semana_obj',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='Entrenamientos por Semana Objetivo'),
        ),
        migrations.CreateModel(
            name='RegistroEjercicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Realización')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, help_text='Completar para ejercicios cardiovasculares.', null=True, verbose_name='Duración (minutos)')),
                ('series', models.PositiveIntegerField(blank=True, null=True, verbose_name='Series')),
                ('repeticiones_por_serie', models.CharField(blank=True, help_text='Ej: 12,10,8 o simplemente 10 si todas iguales.', max_length=100, null=True, verbose_name='Repeticiones por Serie')),
                ('peso_utilizado_kg', models.CharField(blank=True, help_text='Ej: 50,50,55 o simplemente 50 si todas iguales.', max_length=100, null=True, verbose_name='Peso Utilizado (kg) por Serie')),
                ('calorias_quemadas_calculadas', models.PositiveIntegerField(default=0, verbose_name='Calorías Quemadas en esta Sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ejercicio', verbose_name='Ejercicio Realizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Ejercicio Realizado',
                'verbose_name_plural': 'Registros de Ejercicios Realizados',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
