# Generated by Django 5.2.1 on 2025-06-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ejercicio_remove_usuario_carbohidratos_objetivo_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(blank=True, choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdominales', 'Abdominales'), ('cardio_general', 'Cardio General')], max_length=20, null=True, verbose_name='Grupo Muscular'),
        ),
        migrations.CreateModel(
            name='NotaDiariaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Nota')),
                ('texto_nota', models.TextField(help_text='Anota aquí cualquier observación general sobre tu actividad física del día.', verbose_name='Notas sobre el Ejercicio del Día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota Diaria de Ejercicio',
                'verbose_name_plural': 'Notas Diarias de Ejercicio',
                'ordering': ['usuario', '-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
