# Generated by Django 5.2.1 on 2025-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_ejercicio_grupo_muscular_notadiariaejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carbohidratos_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=265, null=True, verbose_name='Carbohidratos Objetivo (g)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grasas_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='Grasas Objetivo (g)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proteinas_objetivo_g',
            field=models.PositiveIntegerField(blank=True, default=150, null=True, verbose_name='Proteínas Objetivo (g)'),
        ),
    ]
